use new batch preview generation
rullzer/previewgenerator pull request #182
Opened 2020-02-16 01:40 UTC by icewind1991

Use the new optimized preview generation methods introduced with https://github.com/nextcloud/server/pull/19495

I've used "feature detection" to remain backwards compatible (and to allow using the new methods if these get backported)

2020-10-23 12:36 UTC, MichaIng commented
Fallback to old method can be removed, since the app now is NC20 compatible only: https://github.com/rullzer/previewgenerator/commit/03665bc120ddd52aa334461b7f271f025b6fc449#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9eR27

2020-12-21 08:56 UTC, rullzer approved these changes

2020-12-21 09:06 UTC, rullzer requested changes
Ah please rebase and indeed it is only 20+ now so all good to just do the 1 way

2021-01-27 11:05 UTC, merged

2022-11-05 23:13 UTC, Glandos commented on lib/Command/PreGenerate.php
> +				);
I know this is very old, but `$specifications` doesn't depend on the current file, so it could be computed only once and set as class member